application: wavetst
version: wz80
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /favicon.ico
  upload: static/favicon.ico
  static_files: static/favicon.ico
- url: /googlecd3f4729bc484a0b.html
  upload: static/googlecd3f4729bc484a0b.html
  static_files: static/googlecd3f4729bc484a0b.html  
- url: .*
  script: entry.py
